### ISSUE TITLE
Clarification on meaning of "Crypto"

### ISSUE THREAD

**Issue by Mars7383** [NONPLAYT/roblox-cheats#1]
In the readme, you express concern over a package called "Crypto" in Fluxus Android, warning that it might be a miner. I'm not a developer or staff member of Fluxus, but I'm certain that "Crypto" is referring to cryptography, not cryptocurrency. 

Judging from class/package names in the screenshot (AES, zip4j), this is likely the source of the library: https://github.com/srikanth-lingala/zip4j. zip4j is a legitimate library that assists developers with interacting with zip archives.

**Comment by NONPLAYT** [comment]
Okay thanks for the problem. my friend found this in december 2022 and i thought it was true without even looking at the lingala.zip4j package. I'll remove it now
